### ISSUE TITLE
registerLoggedInUser fail to register the request User

### ISSUE THREAD

**Issue by jorgecavaleiro** [shahednasser/medusa-1.8-marketplace-tutorial#3]
Hi,
I'm following, step-by-step, the tutorial. The only difference I have is that I'm using the latest medusajs packages ("@medusajs/medusa": "^1.10.0").
When I start the project, I get the error:

AwilixResolutionError: Could not resolve 'loggedInUser'.
Resolution path: loggedInUser
    at resolve (....\node_modules\awilix\lib\container.js:252:23)
    at Object.get (....\node_modules\awilix\lib\container.js:66:33)
    at new StoreService (....\dist\services\store.js:14:44)
    at TransactionBaseService.withTransaction 

When calling the endpoint '/admin/store' from Postman, using 'Bearer [APKey]' as 'Authorization' header, the 'registerLoginUser ' is called but the condition: 'if (req.user && req.user.userId)' returns false.

I thak you for any help/direction.

Best

**Comment by adevinwild** [comment]
Same there is an issue with that CORS Regex, so I decided to add manually the middlewares on each routes inside the `src/api/index.ts`

> i.e router.use("/admin/store", registerLoggedInUser())

**Comment by jorgecavaleiro** [comment]
It seems a different issue for me. When an Api request is made the 'registerLoggedInUser' midleware is called. But the user is not available. I wonder if there is some issue related to getting the user from the 'api_token' sent in the request...

**Comment by jorgecavaleiro** [comment]
Maybe here: 

			**validateSecurity**: {
				handlers: {
					ApiKeyAuth: async (
						req: express.Request,
						_scopes: unknown,
						schema: OpenAPIV3.ApiKeySecurityScheme,
					): Promise<boolean> => {
						const apiKey = req.headers[schema.name.toLowerCase()] as string;
						const user = await Db.collections.User.findOne({
							where: { apiKey },
							relations: ['globalRole'],
						});

						**if (!user) return false;**

**Comment by jorgecavaleiro** [comment]
SOLVED: When the request is made from the API (ex: through postman), the req.userId is undefined.

Had to change the 'registerLoggedInUser' 

  // Request from API
  if (req.user && req.user.id) {
    const userService = 
      req.scope.resolve("userService") as UserService
    loggedInUser = await userService.retrieve(req.user.id)

    console.log('\x1b[33m User: %s \x1b[0m', loggedInUser.email);
  } 

  // Request from Admin app
  if (req.user && req.user.userId) {
    const userService = 
      req.scope.resolve("userService") as UserService
    loggedInUser = await userService.retrieve(req.user.userId)

    console.log('\x1b[33m User: %s \x1b[0m', loggedInUser.email);
  }
